apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-db-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
      - name: db
        image: mysql:5.7 
        ports:
        - name: blog-db-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: db-password
              #use the secrets.yml, but make sure that is not readable by the user.
---
apiVersion: v1
kind: Service
metadata:
  name: blog-db-svc
spec:
  ports:
  - port: 3306
    targetPort: blog-db-port
    protocol: TCP
  selector:
    app: blog-db
  type: ClusterIP