apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: myspace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: no-quota
        image: nginx
        ports:
        - name: nginxport
          containerPort: 80
#        resources:
#          requests:
#            cpu: 200m
#            memory: 200m
#          limits:
#            cpu: 200m
#            memory: 200m
