apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: nginx:alpine
        command: 
         - "bin/sh"
         - "-c"
         - "date"
      restartPolicy: Never
      #Used for a batch update or alike - one time operations
      #you do not want the pod up, once it (container within) has exited the job successfully