apiVersion: v1
kind: Service
metadata:
  name: hw-svc
spec:
  ports:
  - port: 8888
    nodePort: 31001
    targetPort: nginxport
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
#Nopeport => exposed to the outside world
#available on nodePort.
