apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-dep
  namespace: myspace
spec:
  # revisionHistoryLimit: 10
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nginx
        image: nginx:alpine 
        ports:
        - name: nginxport
          containerPort: 80
      # nodeSelector:
      #   boxtype: heavyspec